### ISSUE TITLE
does not release threads after window is closed

### ISSUE THREAD

**Issue by ychakiris** [borodust/bodge-ui-window#1]
The README directions work fine. There are some side effects of opening and closing windows since threads that the window uses never seem to get released.

**Comment by borodust** [comment]
Ouch! Thanks. That was actually a correct behavior, just not the obvious one: windows were hid, but not closed. I changed default behavior to close windows on hiding.

**Comment by borodust** [comment]
I also updated `testing` dist. `(ql:update-all-dists)` should deliver updated version of the library to you.

**Comment by Giels** [comment]
I have the same issue as of the latest version:
```
You already have the latest version of "org.borodust.bodge": 20200824150336.
```

I also tried doing
```
(defmethod bodge-ui-window:on-ui-close ((this main-window))
  (bodge-host:close-window this))
```

But this had no effect either. If I use a button inside the UI registered with a callback that evaluates the same method, however, the thread is released correctly.
